security:
    encoders:
        mholt\txtAHolic\ServerBundle\Entity\User:
            algorithm: bcrypt
            
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        
    providers:
        users:
            entity: { class: UserBundle:User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        default:
            pattern: ^/
            anonymous: ~
            stateless: true
            wsse: true

    access_control:
        - { path: ^/users/register$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/users/auth$, roles: ROLE_USER }
        - { path: ^/, roles: ROLE_AUTHED_SESSION }