security:
    encoders:
        mholt\txtAHolic\ServerBundle\Entity\User:
            algorithm: bcrypt
            
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        
    providers:
        users:
            entity: { class: UserBundle:User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: /users/login
                check_path: /users/login_check

    access_control:
        - { path: ^/users/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/users$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }