parameters:
#    user.example.class: mholt\txtAHolic\UserBundle\Example

services:
    wsse.security.authentication.provider:
        class: mholt\txtAHolic\UserBundle\Security\Provider\WsseProvider
        arguments: ["", "%kernel.cache_dir%/security/nonces"]

    wsse.security.authentication.listener:
        class: mholt\txtAHolic\UserBundle\Security\Firewall\WsseListener
        arguments: ["@security.context", "@security.authentication.manager"]
