parameters:
#    user.example.class: mholt\txtAHolic\UserBundle\Example

services:
    wsse.security.authentication.provider:
        class: mholt\txtAHolic\UserBundle\Security\Provider\WsseProvider
        arguments: ["", "@doctrine.orm.entity_manager"]

    wsse.security.authentication.listener:
        class: mholt\txtAHolic\UserBundle\Security\Firewall\WsseListener
        arguments: ["@security.context", "@security.authentication.manager"]
