parameters:
#    server.example.class: mholt\txtAHolic\ServerBundle\Example

services:
#    server.example:
#        class: %server.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
